name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger workflow on version tags like v1.0.0

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish application
        run: dotnet publish CsvConverter/CsvConverter.csproj -c Release -o out

      - name: Archive binaries
        run: |
          mkdir -p release
          zip -r release/CsvConverter-${GITHUB_REF_NAME}.zip out/

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: release/CsvConverter-${{ github.ref_name }}.zip
