name: Build and Release Application Files

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: latest

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        
    - name: Extract Version
      id: get_version
      uses: battila7/get-version-action@v2.2.1

    - name: Set project version
      id: set_version
      uses: vers-one/dotnet-project-version-updater@v1.6
      with:
        file: "CsvConverter/CsvConverter.csproj"
        version: ${{ steps.get_version.outputs.version-without-v }}

    - name: Restore dependencies
      run: dotnet restore "CsvConverter/CsvConverter.csproj"

    - name: Build solution
      run: dotnet build "CsvConverter/CsvConverter.csproj" --configuration Release

    # Publish the self-contained application
    - name: Publish Self-Contained Version
      run: dotnet publish "CsvConverter/CsvConverter.csproj" -c Release -o ./publish/selfcontained /p:SelfContained=true /p:RuntimeIdentifier=win-x86 /p:PublishSingleFile=true

    - name: Create zip archive (Self-Contained)
      run: |
        powershell Compress-Archive -Path ./publish/selfcontained/* -DestinationPath ./CsvConverter_SelfContained.zip

    # Publish the framework-dependent application
    - name: Publish Framework-Dependent Version
      run: dotnet publish "CsvConverter/CsvConverter.csproj" -c Release -o ./publish/frameworkdependent /p:SelfContained=false /p:RuntimeIdentifier=win-x86 /p:PublishSingleFile=false

    - name: Create zip archive (Framework-Dependent)
      run: |
        powershell Compress-Archive -Path ./publish/frameworkdependent/* -DestinationPath ./CsvConverter_FrameworkDependent.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: notes/${{ github.ref_name }}.md  # Reference the correct release notes file based on the tag
        draft: false
        prerelease: false

    - name: Upload Self-Contained Version
      id: upload-release-asset-selfcontained
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CsvConverter_SelfContained.zip
        asset_name: CsvConverter_SelfContained.zip
        asset_content_type: application/zip
        label: "CsvConverter Self-Contained Version"

    - name: Upload Framework-Dependent Version
      id: upload-release-asset-frameworkdependent
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CsvConverter_FrameworkDependent.zip
        asset_name: CsvConverter_FrameworkDependent.zip
        asset_content_type: application/zip
        label: "CsvConverter Framework-Dependent Version"
