name: Release with Tag Version

on:
  push:
    tags:
      - 'v*.*.*' # Match version tags like v1.0.0

jobs:
  release:
    runs-on: windows-latest # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version in .csproj
        run: |
          echo "Updating version in .csproj to ${VERSION}"
          powershell -Command "(Get-Content CsvConverter/CsvConverter.csproj) -replace '<Version>.*</Version>', '<Version>${VERSION}</Version>' | Set-Content CsvConverter/CsvConverter.csproj"

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Publish self-contained version
      - name: Publish self-contained application
        run: dotnet publish CsvConverter/CsvConverter.csproj -c Release -o bin\Publish\SelfContained /p:SelfContained=true /p:RuntimeIdentifier=win-x86 /p:PublishSingleFile=true /p:PublishReadyToRun=false

      # Publish framework-dependent version
      - name: Publish framework-dependent application
        run: dotnet publish CsvConverter/CsvConverter.csproj -c Release -o bin\Publish\FrameworkDependent /p:SelfContained=false /p:RuntimeIdentifier=win-x86 /p:PublishSingleFile=false /p:PublishReadyToRun=false

      # Archive self-contained version
      - name: Archive self-contained binaries
        run: |
          mkdir release
          powershell Compress-Archive -Path "bin\Publish\SelfContained\*" -DestinationPath "release\CsvConverter-SelfContained-${{ env.VERSION }}.zip"

      # Archive framework-dependent version
      - name: Archive framework-dependent binaries
        run: |
          powershell Compress-Archive -Path "bin\Publish\FrameworkDependent\*" -DestinationPath "release\CsvConverter-FrameworkDependent-${{ env.VERSION }}.zip"

      # Create GitHub Release with Release Notes
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: notes/${{ github.ref_name }}.md
          draft: false
          prerelease: false

      # Upload self-contained version
      - name: Upload Self-Contained Version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/CsvConverter-SelfContained-${{ env.VERSION }}.zip
          asset_name: CsvConverter-SelfContained-${{ env.VERSION }}.zip
          asset_content_type: application/zip
          label: "CsvConverter Self-Contained Version"

      # Upload framework-dependent version
      - name: Upload Framework-Dependent Version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/CsvConverter-FrameworkDependent-${{ env.VERSION }}.zip
          asset_name: CsvConverter-FrameworkDependent-${{ env.VERSION }}.zip
          asset_content_type: application/zip
          label: "CsvConverter Framework-Dependent Version"
